export const skills = [
  { name: 'JavaScript', icon: 'logos:javascript' },
  { name: 'TypeScript', icon: 'logos:typescript-icon' },
  { name: 'Java', icon: 'logos:java' },
  { name: 'C#', icon: 'devicon:csharp' },
  { name: 'HTML', icon: 'logos:html-5' },
  { name: 'CSS', icon: 'logos:css-3' },
  { name: 'SQL Server', icon: 'devicon:microsoftsqlserver' },
  { name: 'MySQL', icon: 'logos:mysql' },
  { name: 'MongoDB', icon: 'logos:mongodb-icon' },
  { name: 'Git', icon: 'logos:git-icon' },
  { name: 'GitHub', icon: 'logos:github-icon' },
  { name: 'GitHub Actions', icon: 'logos:github-actions' },
  { name: 'React', icon: 'logos:react' },
  { name: 'Angular', icon: 'logos:angular-icon' },
  { name: 'Node.js', icon: 'logos:nodejs-icon' },
  { name: 'ASP.NET MVC', icon: 'devicon:dot-net' },
  { name: 'Unity', icon: 'logos:unity' },
  { name: 'Game Development', icon: 'mdi:controller-classic' }
];
